# Generated by Django 4.1 on 2022-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='junior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lead',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='middle',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='senior',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=1000, null=True),
        ),
    ]
